### ISSUE TITLE
Installation ccl failed on FreeBSD 9.1 amd64

### ISSUE THREAD

**Issue by kenoss** [KeenS/CIM#53]
I use FreeBSD 9.1 amd64.

Installation of ccl hangs as the following:

```shell
$ cim install ccl # ccl-1.10
ccl-1.10 installation started.
Downloading archive.
Expanding archive.
Building ccl-1.10
```

It is because kernel installation failed and entered debugger:

```shell
$ tail ~/.cim/log/ccl-1.10/build.log
;Loading #P"/usr/home/keno/.cim/src/ccl-1.10/level-0/l0-pred.fx32fsl"...
;Loading #P"/usr/home/keno/.cim/src/ccl-1.10/level-0/l0-symbol.fx32fsl"...
;Loading #P"/usr/home/keno/.cim/src/ccl-1.10/level-0/l0-utils.fx32fsl"...
;Loading #P"/usr/home/keno/.cim/src/ccl-1.10/level-0/nfasload.fx32fsl"...
;Wrote bootstrapping image: #P"/usr/home/keno/.cim/src/ccl-1.10/fx86-boot32"
;Building lisp-kernel ...
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip evaluation of (rebuild-ccl :full t)
> Type :? for other options.
1 > %
```

It seems CIM to try install ccl for FreeBSD x86, does't it?

FYI, make under `~/.cim/src/ccl-1.10/lisp-kernel/freebsdx8664` successes and
under `~/.cim/src/ccl-1.10/lisp-kernel/freebsdx8632` fails.

**Comment by KeenS** [comment]
@kenoss Thank you for reporting. I tried on FreeBSD10 but this didn't represented. Wait a moment before I get FreeBSD 9.1. Recently, my network connectivity is unstable...

**Comment by kenoss** [comment]
I'm OK.  I've installed CCL using pkg, and I'll update this PC sometime soon.
